project:
  type: website

website:
  title: "AutoML Eindhoven"
  navbar:
    background: light
    logo: "images/logo.png"
    collapse-below: lg
    left:
      - index.qmd
      - text: "Research"
        menu: 
          - file: research/projects.qmd
          - file: research/publications.qmd
          - file: research/blog.qmd
      - software/software.qmd
      - people/people.qmd
    right:
      - icon: github
        href: https://github.com/openml-labs/website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true